# Generated by Django 4.2.3 on 2023-08-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_hdijehdeh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='hdijehdeh',
        ),
    ]
