# Generated by Django 4.2.4 on 2023-08-17 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
